### ISSUE TITLE
Plugin not working?

### ISSUE THREAD

**Issue by socialchap** [gavinmn/obsidian-things-link#11]
Installed on a vault (with Minimal theme plus a few other plugins)...
Cannot see commands in Command palette. Works in another vault with different themes and some different plugins.

- Disabled all other plugins - still not working.
- Changed theme to default - still not working.
- Uninstalled all other plugins - still not working.

(BTW, restarted Obsidian after each step)...

Any ideas? Thanks in advance...

**Comment by gavinmn** [comment]
Have you reinstalled the plugin? There is no reason this shouldn't be working on the default vault or one with custom themes, plugins, settings.

**Comment by socialchap** [comment]
Hi Gavin,
Thanks for responding 👍 
Yes, I have reinstalled, and done the usual restart etc. I have again tried it in other existing and new vaults, and it works fine, therefore I must assume it is an issue with another plugin - going to try reverting my existing vault to a default setting and see what happens...

**Comment by socialchap** [comment]
Hmm, I think I'm eating humble pie...I seem to have missed the issue that the plugin works only in editing mode :( I do apologise...feel free to delete this thread!
