### ISSUE TITLE
[Feature] Use advanced-uri if available

### ISSUE THREAD

**Issue by huyz** [gavinmn/obsidian-things-link#12]
For more durable permalinks, it would be nice if this plugin detected whether https://github.com/Vinzent03/obsidian-advanced-uri/ was installed and enabled, triggered that plugin's creation of a link (thus adding the "uid" field to the frontmatter), and then pasted that link into Things.

Instead of the fragile `obsidian://open` URI, we'd get a more durable `obsidian://advanced-uri` link.

**Comment by danielh-official** [comment]
Hi, @huyz . The README states that the project is no longer supported. I've forked it to my account and

- Refactored the code to be a bit more manageable
- Added automated testing

On the roadmap is making the link given to Things more durable, and using Advanced URI is one solution I've considered. The goal is to publish **Things Link 2** to Obsidian with the new features added in. 

Please let me know if you have any feedback.

The repository is [here](https://github.com/danielh-official/obsidian-things-link-2).

**Comment by gavinmn** [comment]
Thanks @danielh-official. I'll update my readme with a link to your fork! I appreciate you picking up support.

**Comment by huyz** [comment]
@danielh-official sweet, thanks

**Comment by huyz** [comment]
@danielh-official a couple of initial requests:
1) Turn on "Issues" on your repo
2) Make it installable via BRAT.

**Comment by danielh-official** [comment]
@huyz Issues have been set up. I will look into BRAT.
